### PR TITLE
We teach a one fella to show some respect to the coal-guys

### PR DESCRIPTION
**Pull request by W1ckedS1ck**
1234567

### CODE REVIEW

**Comment by dowell007** [comment]
niga niga

**Comment by dowell007** [comment]
niga niga

**Comment by W1ckedS1ck** [comment]
123

**Comment by dowell007** [comment]
you should teach other people fuking niga

**Comment by W1ckedS1ck** [comment]
But how???
I ca't fucking this black faggots
my wife is restrict me to do that!!

**Pull request closed without merging**
